/*-----------------------
   POPMENU.H header file
  -----------------------*/

#define ID_RESOURCE      1

#define IDM_NEW          1
#define IDM_OPEN         2
#define IDM_SAVE         3
#define IDM_SAVEAS       4
#define IDM_ABOUT        5
#define IDM_CUT          6
#define IDM_COPY         7
#define IDM_PASTE        8
#define IDM_CLEAR        9
#define IDM_RED         10
#define IDM_GREEN       11
#define IDM_BLUE        12
#define IDM_SMALL       13
#define IDM_MEDIUM      14
#define IDM_LARGE       15
#define IDM_SLOW        16
#define IDM_MEDSPEED    17
#define IDM_FAST        18
